name: Deploy to Preview Channel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm ci
      - run: CI='' npm run build
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//09hH9cA_SfnIfCgYIARAAGAkSNwF-L9Ir7pe6QNBZqQwyF-aLn7yr7j7AM1qTYNLTN8C1CnUrI7vBNb65XNVcpsYZpDazyPvVJic
